FROM nnvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
LABEL maintainer="ajex1988@gmail.com"
# update && install
RUN apt update && apt install -y python3.7 \
vim \
python-numpy \
openssh-server \
python-pip \
unzip \
gdb